"""
REQUIRE-X JSON & Markdown Exporters
"""

import json
from typing import Dict, Any
from require_x.models.schema import SRSAnalysisReport


class JSONReportExporter:
    """Exports master report to structured JSON."""

    @classmethod
    def to_json_str(cls, report: SRSAnalysisReport) -> str:
        return report.model_dump_json(indent=2)

    @classmethod
    def to_dict(cls, report: SRSAnalysisReport) -> Dict[str, Any]:
        return report.model_dump()


class MarkdownReportExporter:
    """Exports master report to GitHub-Flavored Markdown."""

    @classmethod
    def to_markdown(cls, report: SRSAnalysisReport) -> str:
        m = report.metrics
        md = []
        md.append(f"# {report.project_title}")
        md.append(f"*Generated by REQUIRE-X Multi-Agent AI Framework on {report.analysis_timestamp}*\n")
        
        md.append("## Executive Summary")
        md.append(report.executive_summary + "\n")

        md.append("## Quality Metrics")
        md.append("| Metric | Value |")
        md.append("| :--- | :--- |")
        md.append(f"| **Total Requirements** | {m.total_requirements} |")
        md.append(f"| **Functional (FR)** | {m.functional_count} |")
        md.append(f"| **Non-Functional (NFR)** | {m.non_functional_count} |")
        md.append(f"| **ISO/IEC/IEEE 29148 Compliance** | {m.iso_compliance_score:.1f}% ({report.compliance_scorecard.grade}) |")
        md.append(f"| **Ambiguity Defect Rate** | {m.ambiguity_rate:.1f}% ({m.ambiguity_count} defects) |")
        md.append(f"| **Traceability Coverage** | {m.traceability_coverage_pct:.1f}% |")
        md.append(f"| **Estimated Story Points** | {m.total_story_points} pts |\n")

        md.append("## ISO/IEC/IEEE 29148:2018 Standards Compliance Scorecard")
        md.append("| Characteristic | Score | Status | Remediation Advice |")
        md.append("| :--- | :--- | :--- | :--- |")
        for c in report.compliance_scorecard.criteria:
            md.append(f"| **{c.criterion_name}** | {c.score:.0f}% | {c.status} | {c.remediation} |")
        md.append("")

        md.append("## Requirements Catalog")
        md.append("| ID | Type | Category | Complexity | Statement |")
        md.append("| :--- | :--- | :--- | :--- | :--- |")
        for r in report.requirements:
            md.append(f"| `{r.id}` | {r.req_type} | {r.category} | {r.complexity} ({r.story_points} pts) | {r.statement} |")
        md.append("")

        if report.ambiguities:
            md.append("## Ambiguity Audit & Suggested Disambiguations")
            md.append("| Req ID | Flaw Category | Severity | Ambiguous Phrase | Suggested ISO Rewrite |")
            md.append("| :--- | :--- | :--- | :--- | :--- |")
            for a in report.ambiguities:
                md.append(f"| `{a.req_id}` | {a.flaw_category} | {a.severity} | *\"{a.ambiguous_text}\"* | {a.suggested_rewrite} |")
            md.append("")

        md.append("## Software Architecture Recommendation")
        md.append(f"**Pattern:** {report.architecture.recommended_pattern}\n")
        md.append(f"**Rationale:** {report.architecture.rationale}\n")
        md.append("```mermaid")
        md.append(report.architecture.mermaid_diagram)
        md.append("```\n")

        md.append("## Requirements Traceability Matrix (RTM)")
        md.append("| Req ID | Requirement Title | Architectural Module | Mapped Test Cases | Status |")
        md.append("| :--- | :--- | :--- | :--- | :--- |")
        for item in report.traceability_matrix:
            tc_str = ", ".join(f"`{tc}`" for tc in item.test_case_ids) if item.test_case_ids else "None"
            md.append(f"| `{item.req_id}` | {item.req_title} | {item.architecture_module} | {tc_str} | {item.status} |")
        md.append("")

        return "\n".join(md)
